resilience4j:
  circuitbreaker:
    instances:
      avaliacaoCB:
        minimumNumberOfCalls: 4
        slidingWindowSize: 8


management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: 'health,prometheus'
  endpoint:
    health:
      show-details: always
      enabled: true
    prometheus:
      enabled: true